name: Issue Monitor

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: write

jobs:
  fetch-post:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute script
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        COOKIES: ${{ secrets.COOKIES }}
      run: |
        echo $COOKIES > $HOME/cookies.json
        python src/main.py --url $ISSUE_BODY --filename $ISSUE_TITLE --cookies $HOME/cookies.json
    - name: Commit and push if it changed
      run: |
        git config --local user.name github-actions[bot]
        git config --local user.email github-actions[bot]@users.noreply.github.com
        git add --all
        git commit -am "Update generated file" || exit 0
    - name: Push to backup branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: backup
